# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180822_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=30),
        ),
    ]
