# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_skill_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.Skill'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
