# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180815_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=50),
        ),
    ]
