# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180815_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Skill'),
        ),
    ]
