# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180817_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(to='projects.Position'),
        ),
    ]
