# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20180818_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='applicants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
