# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180818_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='related_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
