# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_position_related_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
