# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180822_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
