# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_position_applicant_chosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='applicant_chosen',
            new_name='filled_by',
        ),
    ]
